\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
getwd()
# Load your packages
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(tidyverse)
# Set your ggplot theme

# Load your datasets

```


# Rationale and Research Questions

  We all chose the topic of tree heights because it is one of the main things that our foursome has in common, as two of us are in the forestry program, while the other two are TFE. In addition, we all found a similar interest of not only how tree heights vary with tree diameter and species, but also these factor in trees of a region unknown to us. 


	The reason we chose this particular dataset is because of none of us have any experience traveling or even reading about Alaska. Our ignorance, combined with the dataset including height, DBH, and species codes, motivated us to use this dataset to answer our questions. Additionally, the data comes from the United States Forest Service, which is a group we all have learned much about and wanted to interact with. 

Q: How does tree height vary across Alaska’s forests?
-	How does this height vary with DBH?
-	How does this height vary with species?



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 



\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
